name: Save Data to JSON

on:
  push:
    paths:
      - 'data.json' # data.json கோப்பு மாறும்போது இது இயங்கும்

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git Config
        run: |
          git config --global user.name "Data Bot"
          git config --global user.email "bot@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add data.json
          git commit -m "Auto-update data.json" || exit 0
          git push
